cookbook/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.category, name='category'),   
    url(r'^recipe/(?P<recipe_name_slug>[\w\-]+)/$', views.recipe, name='recipe'),
    url(r'^list$', views.recipe_list, name='recipe_list')
]

mamilinda_cookbook/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('cookbook.urls')),
    url(r'^cookbook/', include('cookbook.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.simple.urls')),
]

cookbook/models.py
from django.db import models
from django.db.models import signals
from django.template.defaultfilters import slugify


class Tag(models.Model):
    # TODO: tags for different things?
    name = models.CharField(max_length=128, unique=True, default='')


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True, default='')
    slug = models.SlugField(unique=True)

    def first_page(self):
        return self.recipe_set.order_by('book_page').first().book_page

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=128)
    slug = models.SlugField(unique=True)
    alt_title = models.CharField(max_length=128, blank=True, null=True)
    book_page = models.IntegerField()
    category = models.ForeignKey(Category)
    intro = models.TextField(blank=True, null=True)
    serves = models.IntegerField(blank=True, null=True)
    serves_upper = models.IntegerField(blank=True, null=True)
    # For easy autosplitting of copypasted ingredients lists
    blob_ingredients = models.TextField(blank=True, null=True)
    instructions = models.TextField()
    preptime = models.IntegerField(blank=True, null=True)
    book_edition = models.IntegerField(blank=True, null=True)

    def next(self):
        firstnext = Recipe.objects.filter(book_page__gt=self.book_page)\
                          .order_by('book_page')\
                          .first()
        # allnext = Recipe.objects.filter(book_page=firstnext.book_page)
        return firstnext

    def previous(self):
        firstprev = Recipe.objects.filter(book_page__lt=self.book_page)\
                          .order_by('-book_page')\
                          .first()
        return firstprev

    def __str__(self):
        return self.title


def createIngredients(sender, instance, created, **kwargs):
    ''' Create ingredients from blob if it isn't empty.'''
    # TODO: This isn't very pretty, probably a better way with
    # forms. How do the admin inline forms do it?
    if instance.blob_ingredients and instance.blob_ingredients != '':
        Ingredient.objects.filter(recipe=instance).delete()
        ingredients = instance.blob_ingredients.split('\r\n')
        for elem in ingredients:
            Ingredient.objects.create(name=elem, recipe=instance)
        instance.blob_ingredients = ''
        instance.save()


signals.post_save.connect(createIngredients, sender=Recipe)


# TODO: unique place + recipe?
class Ingredient(models.Model):
    name = models.CharField(max_length=256)
    recipe = models.ForeignKey(Recipe)
    # TODO: use latest djfractions with DecimalFractionField?
    quantity = models.DecimalField(null=True, blank=True,
                                   max_digits=10,
                                   decimal_places=5)
    units_choices = (
        ('tsp', 'teaspoon'),
        ('tbl', 'tablespoon'),
        ('cup', 'cup'),
        ('oz', 'ounce'),
        ('lb', 'pound'),
        ('dash', 'dash',),
        ('can', 'can'),
        ('qt', 'quart'),
        ('g', 'grams'),
        ('ml', 'millileters'),
        ('l', 'liters')
        )

    units = models.CharField(max_length=40,
                             choices=units_choices,
                             null=True, blank=True)

    place = models.IntegerField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.place:
            existing_places = Ingredient.objects.filter(recipe=self.recipe)\
                                                .order_by('-place')
            if existing_places:
                self.place = existing_places[0].place + 1
            else:
                self.place = 1
        super(Ingredient, self).save(*args, **kwargs)

    def __str__(self):
        quantity = '{:.2f}'.format(self.quantity) if self.quantity else ''
        units = self.units if self.units else ''
        # TODO: pretty repr with proper fraction quantities
        return '{} {} {}'.format(quantity, units, self.name)

    class Meta:
        # unique_together =
        pass

cookbook/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
from django.contrib.auth.decorators import login_required

from cookbook.models import Category, Recipe, Ingredient
from .filters import RecipeFilter


def index(request):
    category_list = Category.objects.order_by('-name')
    context_dict = {'categories': category_list}
    return render(request, 'cookbook/index.html', context_dict)


def category(request, category_name_slug):
    context_dict = {}

    category = get_object_or_404(Category, slug=category_name_slug)
    context_dict['category_name'] = category.name

    recipes = Recipe.objects.filter(category=category)
    context_dict['recipes'] = recipes
    context_dict['category'] = category

    return render(request, 'cookbook/category.html', context_dict)


@login_required
def recipe(request, recipe_name_slug):
    context_dict = {}
    recipe = get_object_or_404(Recipe, slug=recipe_name_slug)
    context_dict['recipe'] = recipe
    ingredients = Ingredient.objects.filter(recipe=recipe).order_by('place')
    context_dict['ingredients'] = ingredients

    return render(request, 'cookbook/recipe.html', context_dict)


def recipe_list(request):
    f = RecipeFilter(request.GET,
                     queryset=Recipe.objects.all().order_by('book_page'))
    return render_to_response('cookbook/recipelist.html', {'filter': f})

cookbook/templates/cookbook/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load cookbook_extras %}

<html>
    <head lang="en">
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Mami Linda's Cookbook - {% block title %}{% endblock %}</title>
    
        <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">

        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/cookbook/">Cookbook</a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'index' %}">Home</a></li>
                        {% if user.is_authenticated %}
                        {% else %}
                        {% endif %}
                            <li><a href="{% url 'index' %}">Index</a></li>
                  </ul>
            </div>
          </div>
        </div>

        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                {% block side_block %}
                {% get_category_list category%}
                {% endblock %}
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
               <div>
                    {% block body_block %}{% endblock %}
                    </div>
            </div>
          </div>
        </div>
        
        <hr />

        <div>
             <ul>

                <li><a href="{% url 'index' %}">Home</a></li>
            </ul>
      </div>
        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
    </body>

</html>            

cookbook/templates/cookbook/category.html
{% extends 'base.html' %}

{% block title %}{{ category_name }}{% endblock %} 

{% block body_block %}

    {% if category %}
    <h1>{{ category_name }}</h1>
        {% if recipes %}
        <ul>
            {% for recipe in recipes %}
            <li><a href="{% url 'recipe' recipe.slug %}">{{ recipe.title }}</a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}
    {% else %}
        The specified category {{ category_name }} does not exist!
    {% endif %}

{% endblock %}

cookbook/templates/cookbook/cats.html
{% if cats %}
    <ul class="nav nav-sidebar">
    {% for c in cats %}
        {% if c == act_cat %} <li  class="active" > {% else  %} <li>{% endif %}
                <a href="{% url 'category'  c.slug %}">{{ c.name }}</a></li>
    {% endfor %}

{% else %}
    <li> <strong >There are no categories present.</strong></li>

    </ul>
{% endif %}

cookbook/templates/cookbook/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %} 

{% block body_block %}
    
    <h1>Mami Linda's Cookbook</h1>
    <a href="{% url 'recipe_list' %}">All recipes</a>


{% endblock %}

cookbook/templates/cookbook/recipe.html
{% extends 'base.html' %}

{% block title %}{{ recipe.title }}{% endblock %}

{% block body_block %}
    <h1>{{ recipe.title }}</h1>

    <p>{{ recipe.intro | linebreaks }}</p>
    {% if recipe.serves %}
        <p>For {{recipe.serves}} 
        {% if recipe.serves_upper %}to {{recipe.serves_upper}}{% endif %}
        persons</p>
    {% endif %}
    {% if ingredients %}
        {% load fractions %}
        <ul>
            {% for ingredient in ingredients %}
            <li>
            {% if ingredient.quantity %}
                {% display_fraction ingredient.quantity %} 
            {% endif %}
            {% if ingredient.get_units_display %}
                {{ ingredient.get_units_display }}{{ ingredient.quantity|pluralize }}
            {% endif %} 
            {{ ingredient.name }}
            </li>
            {% endfor %}
        </ul>
    {% endif %}
        <p>{{ recipe.instructions | linebreaks }}</p>

    <nav>
        <ul class="pager">
        {% if recipe.previous %}
            <li class="previous"><a href="{% url 'recipe' recipe.previous.slug %}">
            <span aria-hidden="true">&larr; </span>{{ recipe.previous.title }}</a></li>
        {% endif %}            
        {% if recipe.next %}
            <li class="next">
            <a href="{% url 'recipe' recipe.next.slug %}">{{ recipe.next.title }}<span aria-hidden="true"> &rarr;</span></a>
            </li>
        {% endif %}
        </ul>
    </nav>
{% endblock %}

cookbook/templates/cookbook/recipelist.html
{% extends 'base.html' %}

{% block title %}All Recipes{% endblock %} 

{% block body_block %}
    <form action="" method="get">
        {{ filter.form.as_p }}
        <input type="submit" />
    </form>
    {% for obj in filter %}
        <a href="/cookbook/recipe/{{ obj.slug}}/">{{ obj.title }}</a><br />
    {% endfor %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load cookbook_extras %}

<html>
    <head lang="en">
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Mami Linda's Cookbook - {% block title %}{% endblock %}</title>
    
        <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">

        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/cookbook/">Cookbook</a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                  <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ user.username }} <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                      <li><a href="{% url 'auth_logout' %}?next=/cookbook/">Sign out</a></li>
                  </ul>
                {% else %}
                  <li>
                      <p class="navbar-btn">
                          <a href="{% url 'auth_login' %}" class="btn btn-success">Sign in</a>
                      </p>
                  </li>

                {% endif %}
              </ul>
            </div>
          </div>
        </div>

        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                {% block side_block %}
                {% get_category_list category%}
                {% endblock %}
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
               <div>
                    {% block body_block %}{% endblock %}
                    </div>
            </div>
          </div>
        </div>
        
        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
    </body>

</html>            